#!/usr/bin/env python3
"""Add official IJV CHIRP modules to PocketCHIRP community candidates.

The IJV download page publishes two direct Python modules and one ZIP bundle for
firmware 3.60. This script downloads those official files, unpacks Python files
from the ZIP in-memory, fingerprints each driver, and merges exact candidates
into community/candidates.json without auto-approving anything.
"""

from __future__ import annotations

import hashlib
import io
import json
import re
import urllib.parse
import urllib.request
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CANDIDATES = ROOT / "community" / "candidates.json"
UA = "PocketCHIRP-IJV-Discovery/1.0"
MAX_DOWNLOAD = 8 * 1024 * 1024
MAX_MEMBER = 2 * 1024 * 1024

OFFICIAL = [
    {
        "kind": "python",
        "firmware": "4.0",
        "url": "https://www.ijvradio.com/Chirp%20plugin/IJV%20V4.0%20Unified.py",
        "label": "IJV V4.0 Unified",
    },
    {
        "kind": "zip",
        "firmware": "3.60",
        "url": "https://www.ijvradio.com/download/IJV_3.60_Chirp.zip",
        "label": "IJV 3.60 CHIRP bundle",
    },
    {
        "kind": "python",
        "firmware": "5.0",
        "url": "https://www.ijvradio.com/Chirp%20plugin/IJV%20V5.0%20Memory.py",
        "label": "IJV V5.0 Memory",
    },
]


def fetch_bytes(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = resp.read(MAX_DOWNLOAD + 1)
    if len(data) > MAX_DOWNLOAD:
        raise RuntimeError(f"Official IJV download too large: {url}")
    return data


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def safe_text(data: bytes) -> str:
    return data.decode("utf-8", errors="replace")


def structural_hints(text: str) -> list[str]:
    checks = [
        ("CloneModeRadio", r"\bCloneModeRadio\b"),
        ("directory.register", r"directory\.register"),
        ("RadioSetting", r"\bRadioSetting\b"),
        ("sync_in", r"\bdef\s+sync_in\b"),
        ("sync_out", r"\bdef\s+sync_out\b"),
    ]
    return [name for name, pattern in checks if re.search(pattern, text)]


def extract_models(text: str) -> list[str]:
    models = []
    for match in re.finditer(r"^\s*MODEL\s*=\s*['\"]([^'\"]+)['\"]", text, re.M):
        value = match.group(1).strip()
        if value and value not in models:
            models.append(value)
    return models


def make_candidate(*, url: str, firmware: str, label: str, filename: str,
                   data: bytes, zip_source: str | None = None) -> dict:
    text = safe_text(data)
    hints = structural_hints(text)
    models = extract_models(text) or [f"UV-K5 V3 / UV-K1 (IJV {firmware})"]
    digest = sha256(data)
    encoded_name = urllib.parse.quote(filename, safe="")
    source_tag = zip_source or url
    key = f"official:ijvradio:{firmware}:{filename}:{digest[:12]}"
    return {
        "candidateKey": key,
        "type": "official-site-file",
        "repository": "ijvradio.com",
        "path": filename,
        "sourceUrl": source_tag,
        "downloadUrl": url if zip_source is None else "",
        "sha256": digest,
        "vendors": ["Quansheng"],
        "models": models,
        "variants": [f"Official IJV firmware {firmware}"],
        "hintsMatched": hints,
        "reasons": ["official IJV download source"],
        "status": "needs-review",
        "historical": firmware == "3.60",
        "releaseTier": "historical" if firmware == "3.60" else "current",
        "displayName": f"Quansheng IJV {firmware} — {label}" + (f" — {filename}" if zip_source else ""),
        "officialSource": True,
        "officialFirmware": firmware,
        "archiveSourceUrl": zip_source or "",
        "archiveMember": filename if zip_source else "",
        "installPackaging": "zip-member" if zip_source else "direct-python",
    }


def main() -> None:
    payload = json.loads(CANDIDATES.read_text(encoding="utf-8"))
    rows = list(payload.get("candidates", []))

    # Remove only prior official-IJV rows generated by this script; preserve mirrors.
    rows = [r for r in rows if not (r.get("repository") == "ijvradio.com" and r.get("officialSource"))]

    added = []
    for item in OFFICIAL:
        raw = fetch_bytes(item["url"])
        if item["kind"] == "python":
            filename = urllib.parse.unquote(urllib.parse.urlparse(item["url"]).path.rsplit("/", 1)[-1])
            added.append(make_candidate(
                url=item["url"], firmware=item["firmware"], label=item["label"],
                filename=filename, data=raw,
            ))
            continue

        with zipfile.ZipFile(io.BytesIO(raw)) as zf:
            members = [m for m in zf.infolist()
                       if not m.is_dir() and m.filename.lower().endswith(".py")]
            if not members:
                raise RuntimeError(f"No Python drivers found in official IJV ZIP: {item['url']}")
            for member in members:
                if member.file_size > MAX_MEMBER:
                    raise RuntimeError(f"IJV ZIP member too large: {member.filename}")
                data = zf.read(member)
                added.append(make_candidate(
                    url=item["url"], firmware=item["firmware"], label=item["label"],
                    filename=member.filename, data=data, zip_source=item["url"],
                ))

    rows.extend(added)
    payload["candidates"] = rows
    payload["candidateCount"] = len(rows)
    payload["officialIjvSource"] = True
    payload["officialIjvCandidateCount"] = len(added)
    CANDIDATES.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    print(f"Added {len(added)} official IJV candidate file(s):")
    for row in added:
        print(f"- {row['displayName']} :: {row['path']} :: {row['sha256'][:12]}")


if __name__ == "__main__":
    main()
